name: build macos
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: build
        run: |
          cd src/macos
          swift build -c release
          mkdir -p ../../artifacts/macos/airobloxbuilder.app/Contents/MacOS
          cp .build/release/airobloxbuilder ../../artifacts/macos/airobloxbuilder.app/Contents/MacOS/airobloxbuilder
          cp ../../src/macos/Info.plist ../../artifacts/macos/airobloxbuilder.app/Contents/Info.plist
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: airobloxbuilder-macos
          path: artifacts/macos/